model_list:
  - model_name: Qwen3.5-0.8B
    litellm_params:
      model: hosted_vllm/Qwen3.5-0.8B
      api_base: http://host.docker.internal:8000
      api_key: not-needed

  - model_name: lfm2-2.6b
    litellm_params:
      model: hosted_vllm/LFM2-2.6B-Q8_0.gguf
      api_base: http://host.docker.internal:8181
      api_key: not-needed

  - model_name: llama3.1
    litellm_params:
      model: ollama/llama3.1
      api_base: http://host.docker.internal:11434

litellm_settings:
  drop_params: True
  success_callback: ["langfuse"]
  failure_callback: ["langfuse"]

environment_variables:
  LANGFUSE_PUBLIC_KEY: os.environ/LANGFUSE_PUBLIC_KEY
  LANGFUSE_SECRET_KEY: os.environ/LANGFUSE_SECRET_KEY
  LANGFUSE_HOST: "http://langfuse-web:3000" 
